# Use root/example as user/password credentials
version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:80
    volumes:
      - ./src:/var/www/html/

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # (this is just an example, not intended to be a production configuration)
    ports:
      - 8036:3306
    volumes:
      - ./db:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
